# Generated by Django 4.2.27 on 2026-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('category', models.CharField(choices=[('HOT', 'Hot Coffee'), ('COLD', 'Cold Coffee'), ('DESSERT', 'Dessert')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP Room')], default='REGULAR', max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='coffee.menuitem')),
            ],
        ),
    ]
