# Generated by Django 4.2.27 on 2026-02-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_bakeryitem_alter_menuitem_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BakeryItem',
        ),
    ]
